name: MinimumProject
version: 0.5
description:
author: Chaoscrasher
main: com.test.main.MinimumProjectPlugin
api-version: 1.12

commands:
  tcom:
    description: Allows you to read the type of a block anywhere in the world!
    usage: use /tcom x y z w to call the test command
